Feat/46 calculate rewards
nickvb96/claim-api pull request #4
Opened 2022-05-24 00:23 UTC by Netail

2022-05-24 18:16 UTC, wooyh2000 requested changes

2022-05-24 18:16 UTC, wooyh2000 commented on src/jobs/calculateRewards.ts
> + * This job runs every ... hours/minutes/seconds for calculating the rewards per user and token.
Change this comment to: This job runs every 8 hours for calculating the rewards per user and token.

2022-05-24 18:16 UTC, wooyh2000 commented on src/jobs/calculateRewards.ts
> +    const MAIN_TRANSFER_ADDRESS = '0x08302cf8648a961c607e3e7bd7b7ec3230c2a6c5';
Consider moving the addresses to the .env file

2022-05-24 18:16 UTC, wooyh2000 commented on src/jobs/calculateRewards.ts
> +    const wallets: IWallet[] = await Wallet.find({ signedUpAt: { $lt: datePreviousWeek } });
You might need to explain what $lt is.

2022-05-24 18:16 UTC, wooyh2000 commented on src/jobs/calculateRewards.ts
> +            console.log('No database rewards found');
Change to console.error.

2022-05-24 18:16 UTC, wooyh2000 commented on src/jobs/calculateRewards.ts
> +            console.log('No contract rewards found');
Change to console.error.

2022-05-24 18:16 UTC, wooyh2000 commented on src/jobs/calculateRewards.ts
> +            if (measurements.length != 7) throw new Error('Insufficient measurements');
Assign 7 to variable.

2022-05-24 18:16 UTC, wooyh2000 commented on src/jobs/calculateRewards.ts
> +            const m = await median(balances);
Change m to a more logical named const, like response or median, for example.

2022-05-24 18:39 UTC, Netail commented on src/jobs/calculateRewards.ts
> + * This job runs every ... hours/minutes/seconds for calculating the rewards per user and token.
But it doesn't run every 8 hours

2022-05-26 17:34 UTC, wooyh2000 requested changes

2022-05-26 17:34 UTC, wooyh2000 commented on src/jobs/calculateRewards.ts
> +    const MAIN_TRANSFER_ADDRESS = '0x08302cf8648a961c607e3e7bd7b7ec3230c2a6c5';
Consider moving the MAIN_TRANSFER_ADDRESS address to the .env file

2022-05-27 15:07 UTC, nickvb96 requested changes
We should leave .env.example & package-lock.json in the repo. 
Otherwise, people will have to explore all files for .env values.

Package-lock because of version locks.

2022-05-27 15:07 UTC, nickvb96 commented on src/jobs/calculateRewards.ts
> +    const datePreviousWeek = getDate(true, new Date('March 15 2022 1:00'), WEEK_DAYS);
Since this is for testing purposes and thus belongs to development, might want to move the hardcoded date into the if of line 39.
If outside of that scope, use the current date.

2022-05-27 15:07 UTC, nickvb96 commented on src/jobs/calculateRewards.ts
> +    const temp = rewards.map((e) => ({
You might want to rename the const, temp isn't really maintainable as it is not self-explanatory.

2022-05-27 15:58 UTC, Netail commented
> We should leave .env.example & package-lock.json in the repo. Otherwise, people will have to explore all files for .env values.
> 
> Package-lock because of version locks.

Package-lock is not removed

2022-05-27 16:44 UTC, wooyh2000 approved these changes

2022-05-27 17:32 UTC, nickvb96 commented
> & package-lock.json in the repo. Otherwise, people will have to explore all files for .env values.
> 
> Package-lock because of versi

Ah yeah, my bad. I see it is still there but over 13.000 lines have been deleted from it. 
I'm unsure as to how big the impact those lines are but I would assume it might be better to restore those.

2022-05-27 17:35 UTC, Netail commented
> > & package-lock.json in the repo. Otherwise, people will have to explore all files for .env values.
> > 
> > Package-lock because of versi
> 
> Ah yeah, my bad. I see it is still there but over 13.000 lines have been deleted from it. 
> I'm unsure as to how big the impact those lines are but I would assume it might be better to restore those.

Shouldn't be a problem, it's a clean one. The main package-lock might have contain old deps, or a few deps got the same versions instead of different ones

2022-05-28 18:33 UTC, nickvb96 approved these changes

2022-05-28 18:36 UTC, merged